fastparcel/fastparcel/fastparcel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from core import views, consumers

from core.customer import views as customer_views
from core.courier import views as courier_views, apis as courier_apis

customer_urlpatters = [
    path('', customer_views.home, name="home"),
    path('profile/', customer_views.profile_page, name="profile"),
    path('payment_method/', customer_views.payment_method_page, name="payment_method"),
    path('create_job/', customer_views.create_job_page, name="create_job"),

    path('jobs/current/', customer_views.current_jobs_page, name="current_jobs"),
    path('jobs/archived/', customer_views.archived_jobs_page, name="archived_jobs"),
    path('jobs/<job_id>/', customer_views.job_page, name="job"),
]

courier_urlpatters = [
    path('', courier_views.home, name="home"),
    path('jobs/available/', courier_views.available_jobs_page, name="available_jobs"),
    path('jobs/available/<id>/', courier_views.available_job_page, name="available_job"),
    path('jobs/current/', courier_views.current_job_page, name="current_job"),
    path('jobs/current/<id>/take_photo/', courier_views.current_job_take_photo_page, name="current_job_take_photo"),
    path('jobs/complete/', courier_views.job_complete_page, name="job_complete"),
    path('jobs/archived/', courier_views.archived_jobs_page, name="archived_jobs"),
    path('profile/', courier_views.profile_page, name="profile"),
    path('payout_method/', courier_views.payout_method_page, name="payout_method"),

    path('api/jobs/available/', courier_apis.available_jobs_api, name="available_jobs_api"),
    path('api/jobs/current/<id>/update/', courier_apis.current_job_update_api, name="current_job_update_api"),
    path('api/fcm-token/update/', courier_apis.fcm_token_update_api, name="fcm_token_update_api"),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', views.home),

    path('sign-in/', auth_views.LoginView.as_view(template_name="sign_in.html")),
    path('sign-out/', auth_views.LogoutView.as_view(next_page="/")),
    path('sign-up/', views.sign_up),
    
    path('customer/', include((customer_urlpatters, 'customer'))),
    path('courier/', include((courier_urlpatters, 'courier'))),
    path('firebase-messaging-sw.js', (TemplateView.as_view(template_name="firebase-messaging-sw.js", content_type="application/javascript",))),
]

websocket_urlpatterns = [
    path('ws/jobs/<job_id>/', consumers.JobConsumer.as_asgi())
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fastparcel/fastparcel/core/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Customer(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  avatar = models.ImageField(upload_to='customer/avatars/', blank=True, null=True)
  phone_number = models.CharField(max_length=50, blank=True)
  stripe_customer_id = models.CharField(max_length=255, blank=True)
  stripe_payment_method_id = models.CharField(max_length=255, blank=True)
  stripe_card_last4 = models.CharField(max_length=255, blank=True)

  def __str__(self):
    return self.user.get_full_name()

class Courier(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  lat = models.FloatField(default=0)
  lng = models.FloatField(default=0)
  paypal_email = models.EmailField(max_length=255, blank=True)
  fcm_token = models.TextField(blank=True)

  def __str__(self):
    return self.user.get_full_name()

class Category(models.Model):
  slug = models.CharField(max_length=255, unique=True)
  name = models.CharField(max_length=255)

  def __str__(self):
    return self.name

class Job(models.Model):
  SMALL_SIZE = "small"
  MEDIUM_SIZE = "medium"
  LARGE_SIZE = "large"
  SIZES = (
    (SMALL_SIZE, 'Small'),
    (MEDIUM_SIZE, 'Medium'),
    (LARGE_SIZE, 'Large'),
  )

  CREATING_STATUS = 'creating'
  PROCESSING_STATUS = 'processing'
  PICKING_STATUS = 'picking'
  DELIVERING_STATUS = 'delivering'
  COMPLETED_STATUS = 'completed'
  CANCELED_STATUS = 'canceled'
  STATUSES = (
    (CREATING_STATUS, 'Creating'),
    (PROCESSING_STATUS, 'Processing'),
    (PICKING_STATUS, 'Picking'),
    (DELIVERING_STATUS, 'Delivering'),
    (COMPLETED_STATUS, 'Completed'),
    (CANCELED_STATUS, 'Canceled'),
  )

  # Step 1
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
  courier = models.ForeignKey(Courier, on_delete=models.CASCADE, null=True, blank=True)
  name = models.CharField(max_length=255)
  description = models.CharField(max_length=255)
  category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
  size = models.CharField(max_length=20, choices=SIZES, default=MEDIUM_SIZE)
  quantity = models.IntegerField(default=1)
  photo = models.ImageField(upload_to='job/photos/')
  status = models.CharField(max_length=20, choices=STATUSES, default=CREATING_STATUS)
  created_at = models.DateTimeField(default=timezone.now)

  # Step 2
  pickup_address = models.CharField(max_length=255, blank=True)
  pickup_lat = models.FloatField(default=0)
  pickup_lng = models.FloatField(default=0)
  pickup_name = models.CharField(max_length=255, blank=True)
  pickup_phone = models.CharField(max_length=50, blank=True)

  # Step 3
  delivery_address = models.CharField(max_length=255, blank=True)
  delivery_lat = models.FloatField(default=0)
  delivery_lng = models.FloatField(default=0)
  delivery_name = models.CharField(max_length=255, blank=True)
  delivery_phone = models.CharField(max_length=50, blank=True)

  # Step 4
  duration = models.IntegerField(default=0)
  distance = models.FloatField(default=0)
  price = models.FloatField(default=0)

  # Extra info
  pickup_photo = models.ImageField(upload_to='job/pickup_photos/', null=True, blank=True)
  pickedup_at = models.DateTimeField(null=True, blank=True)

  delivery_photo = models.ImageField(upload_to='job/delivery_photos/', null=True, blank=True)
  delivered_at = models.DateTimeField(null=True, blank=True)

  def __str__(self):
    return self.description

class Transaction(models.Model):
  IN_STATUS = "in"
  OUT_STATUS = "out"
  STATUSES = (
    (IN_STATUS, 'In'),
    (OUT_STATUS, 'Out'),
  )

  stripe_payment_intent_id = models.CharField(max_length=255, unique=True)
  job = models.ForeignKey(Job, on_delete=models.CASCADE)
  amount = models.FloatField(default=0)
  status = models.CharField(max_length=20, choices=STATUSES, default=IN_STATUS)
  created_at = models.DateTimeField(default=timezone.now)

  def __str__(self):
    return self.stripe_payment_intent_id

fastparcel/fastparcel/core/courier/forms.py
from django import forms
from core.models import Courier

class PayoutForm(forms.ModelForm):
  class Meta:
    model = Courier
    fields = ('paypal_email',)

fastparcel/fastparcel/core/customer/forms.py
from django import forms
from django.contrib.auth.models import User

from core.models import Customer, Job

class BasicUserForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ('first_name', 'last_name')

class BasicCustomerForm(forms.ModelForm):
  class Meta:
    model = Customer
    fields = ('avatar',)

class JobCreateStep1Form(forms.ModelForm):
  class Meta:
    model = Job
    fields = ('name', 'description', 'category', 'size', 'quantity', 'photo')

class JobCreateStep2Form(forms.ModelForm):
  pickup_address = forms.CharField(required=True)
  pickup_name = forms.CharField(required=True)
  pickup_phone = forms.CharField(required=True)

  class Meta:
    model = Job
    fields = ('pickup_address', 'pickup_lat', 'pickup_lng', 'pickup_name', 'pickup_phone')

class JobCreateStep3Form(forms.ModelForm):
  delivery_address = forms.CharField(required=True)
  delivery_name = forms.CharField(required=True)
  delivery_phone = forms.CharField(required=True)

  class Meta:
    model = Job
    fields = ('delivery_address', 'delivery_lat', 'delivery_lng', 'delivery_name', 'delivery_phone')

fastparcel/fastparcel/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class SignUpForm(UserCreationForm):
  email = forms.EmailField(max_length=250)
  first_name = forms.CharField(max_length=150)
  last_name = forms.CharField(max_length=150)

  class Meta:
    model = User
    fields = ('email', 'first_name', 'last_name', 'password1', 'password2')

  def clean_email(self):
    email = self.cleaned_data['email'].lower()
    if User.objects.filter(email=email):
      raise ValidationError("This email address already exists.")
    return email

fastparcel/fastparcel/core/courier/views.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.conf import settings
from django.contrib import messages

from core.models import *
from core.courier import forms

@login_required(login_url="/sign-in/?next=/courier/")
def home(request):
    return redirect(reverse('courier:available_jobs'))

@login_required(login_url="/sign-in/?next=/courier/")
def available_jobs_page(request):
    return render(request, 'courier/available_jobs.html', {
        "GOOGLE_MAP_API_KEY": settings.GOOGLE_MAP_API_KEY
    })

@login_required(login_url="/sign-in/?next=/courier/")
def available_job_page(request, id):
    job = Job.objects.filter(id=id, status=Job.PROCESSING_STATUS).last()

    if not job:
        return redirect(reverse('courier:available_jobs'))

    if request.method == 'POST':
        job.courier = request.user.courier
        job.status = Job.PICKING_STATUS
        job.save()

        try:
            layer = get_channel_layer()
            async_to_sync(layer.group_send)("job_" + str(job.id), {
                'type': 'job_update',
                'job': {
                    'status': job.get_status_display(),
                }
            })
        except:
            pass

        return redirect(reverse('courier:available_jobs'))

    return render(request, 'courier/available_job.html', {
        "job": job
    })

@login_required(login_url="/sign-in/?next=/courier/")
def current_job_page(request):
    job = Job.objects.filter(
        courier=request.user.courier,
        status__in = [
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    ).last()

    return render(request, 'courier/current_job.html', {
        "job": job,
        "GOOGLE_MAP_API_KEY": settings.GOOGLE_MAP_API_KEY
    })

@login_required(login_url="/sign-in/?next=/courier/")
def current_job_take_photo_page(request, id):
    job = Job.objects.filter(
        id=id,
        courier=request.user.courier,
        status__in=[
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    ).last()

    if not job:
        return redirect(reverse('courier:current_job'))

    return render(request, 'courier/current_job_take_photo.html', {
        "job": job
    })

@login_required(login_url="/sign-in/?next=/courier/")
def job_complete_page(request):
    return render(request, 'courier/job_complete.html')

@login_required(login_url="/sign-in/?next=/courier/")
def archived_jobs_page(request):
    jobs = Job.objects.filter(
        courier=request.user.courier,
        status=Job.COMPLETED_STATUS
    )

    return render(request, 'courier/archived_jobs.html', {
        "jobs": jobs
    })

@login_required(login_url="/sign-in/?next=/courier/")
def profile_page(request):
    jobs = Job.objects.filter(
        courier=request.user.courier,
        status=Job.COMPLETED_STATUS
    )

    total_earnings = round(sum(job.price for job in jobs) * 0.8, 2)
    total_jobs = len(jobs)
    total_km = sum(job.distance for job in jobs)

    return render(request, 'courier/profile.html', {
        "total_earnings": total_earnings,
        "total_jobs": total_jobs,
        "total_km": total_km
    })

@login_required(login_url="/sign-in/?next=/courier/")
def payout_method_page(request):
    payout_form = forms.PayoutForm(instance=request.user.courier)

    if request.method == 'POST':
        payout_form = forms.PayoutForm(request.POST, instance=request.user.courier)
        if payout_form.is_valid():
            payout_form.save()

            messages.success(request, "Payout address is updated.")
            return redirect(reverse('courier:profile'))

    return render(request, 'courier/payout_method.html', {
        'payout_form': payout_form
    })

fastparcel/fastparcel/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login

from . import forms

# Create your views here.
def home(request):
    return render(request, 'home.html')

def sign_up(request):
    form = forms.SignUpForm()

    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data.get('email').lower()

            user = form.save(commit=False)
            user.username = email
            user.save()

            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/')

    return render(request, 'sign_up.html', {
        'form': form
    })

fastparcel/fastparcel/core/templates/customer/base.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% url 'customer:create_job' as create_job_url %}
{% url 'customer:profile' as profile_url %}
{% url 'customer:current_jobs' as current_jobs_url %}
{% url 'customer:archived_jobs' as archived_jobs_url %}
{% url 'customer:payment_method' as payment_method_url %}

<div class="container bg-light mt-4 pt-3 pb-3">
  <div class="row">
    <div class="col-lg-4">
      <div class="text-center">
        <img
          src="{% if request.user.customer.avatar %}{{ request.user.customer.avatar.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}"
          alt="" class="rounded-circle mb-2" width="100" height="100">
        <h4>{{ request.user.get_full_name }}</h4>
        <p class="text-secondary">{{ request.user.email }}</p>
      </div>

      <div class="list-group mt-5">
        <a href="{% url 'customer:create_job' %}"
          class="list-group-item list-group-item-action {% if request.path == create_job_url %}active{% endif %}">Create
          a Job
        </a>
        <a href="{% url 'customer:current_jobs' %}"
          class="list-group-item list-group-item-action {% if request.path == current_jobs_url or request.path == archived_jobs_url %}active{% endif %}">My
          Jobs</a>
        <a href="{% url 'customer:profile' %}"
          class="list-group-item list-group-item-action {% if request.path == profile_url %}active{% endif %}">Profile
          Information</a>
        <a href="{% url 'customer:payment_method' %}"
          class="list-group-item list-group-item-action {% if request.path == payment_method_url %}active{% endif %}">Payment
          Method</a>
      </div>

    </div>
    <div class="col-lg-8">
      {% block main %}

      {% endblock %}
    </div>
  </div>
</div>

{% endblock %}

fastparcel/fastparcel/core/templates/customer/create_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block head %}

<script
  src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAP_API_KEY }}&callback=initMap&libraries=places&v=weekly"
  defer></script>

<style>
  #pills-tab a {
    color: black;
  }

  #pills-tab a:hover {
    color: orange;
    text-decoration: none;
  }

  #pills-tab a.active {
    color: orange;
  }

  #pickup-map,
  #delivery-map {
    height: 100%;
  }
</style>
{% endblock %}

{% block content %}
<div class="container mt-4">
  <div class="row">
    <!-- LEFT SIDE -->
    <div class="col-lg-4">
      <div class="card">
        <div class="card-header">
          JOB SUMMARY
        </div>
        <div class="card-body">
          {% if not job %}
          <p>A summary of your job information will appear here</p>
          {% else %}

          {% if step > 1 %}
          <h4>{{ job.name }}</h4>
          <span>{{ job.quantity }} Item</span><br />
          <span>{{ job.get_size_display }} Job</span>
          {% endif %}

          {% if step > 2 %}
          <hr />
          <p class="text-secondary"><small><b>PICKUP</b></small></p>
          <h4>{{ job.pickup_name }}</h4>
          <span>{{ job.pickup_address }}</span><br />
          {% endif %}

          {% if step > 3 %}
          <hr />
          <p class="text-secondary"><small><b>DELIVERY</b></small></p>
          <h4>{{ job.delivery_name }}</h4>
          <span>{{ job.delivery_address }}</span><br />
          {% endif %}

          {% endif %}
        </div>
      </div>
    </div>

    <!-- RIGHT SIDE -->
    <div class="col-lg-8">

      <!-- Step tabs -->
      <div class="card mb-5">
        <div class="card-body">

          <ul class="nav nav-pills nav-justified align-items-center mb-3" id="pills-tab" role="tablist">
            <li class="nav-item" role="presentation">
              <a class="{% if step == 1 %}active{% endif %}" id="pills-info-tab" data-toggle="pill" href="#pills-info"
                role="tab" aria-controls="pills-info" aria-selected="true">Item Info</a>
            </li>
            <i class="fas fa-chevron-right"></i>
            <li class="nav-item" role="presentation">
              <a class="{% if step == 2 %}active{% endif %}" id="pills-pickup-tab" data-toggle="pill"
                href="#pills-pickup" role="tab" aria-controls="pills-pickup" aria-selected="false">Pickup</a>
            </li>
            <i class="fas fa-chevron-right"></i>
            <li class="nav-item" role="presentation">
              <a class="{% if step == 3 %}active{% endif %}" id="pills-delivery-tab" data-toggle="pill"
                href="#pills-delivery" role="tab" aria-controls="pills-delivery" aria-selected="false">Delivery</a>
            </li>
            <i class="fas fa-chevron-right"></i>
            <li class="nav-item" role="presentation">
              <a class="{% if step == 4 %}active{% endif %}" id="pills-payment-tab" data-toggle="pill"
                href="#pills-payment" role="tab" aria-controls="pills-payment" aria-selected="false">Payment</a>
            </li>
          </ul>

        </div>
      </div>

      <!-- Step forms -->
      <b>CREATE A JOB</b>
      <div class="tab-content" id="pills-tabContent">

        <!-- Step 1 -->
        <div class="tab-pane fade {% if step == 1 %}show active{% endif %}" id="pills-info" role="tabpanel"
          aria-labelledby="pills-info-tab">
          <h1>Item Info</h1>

          <form method="POST" enctype="multipart/form-data">
            <b class="text-secondary">Item Information</b><br />
            <div class="card bg-white mt-2 mb-5">
              <div class="card-body">
                {% csrf_token %}
                {% bootstrap_form step1_form %}
              </div>
            </div>
            <input type="hidden" name="step" value="1">
            <button type="submit" class="btn btn-warning">Save & Continue</button>
          </form>
        </div>

        <!-- Step 2 -->
        <div class="tab-pane fade {% if step == 2 %}show active{% endif %}" id="pills-pickup" role="tabpanel"
          aria-labelledby="pills-pickup-tab">
          <h1>Pickup</h1>

          <form method="POST" enctype="multipart/form-data">
            <b class="text-secondary">Pickup Information</b><br />
            <div class="card bg-white mt-2 mb-5">
              <div class="card-body">

                <div class="row">
                  <div class="col-lg-8">
                    {% csrf_token %}
                    {% bootstrap_form step2_form exclude='pickup_lat, pickup_lng' %}
                    <input hidden id="pickup_lat" name="pickup_lat" value="{{ job.pickup_lat }}" />
                    <input hidden id="pickup_lng" name="pickup_lng" value="{{ job.pickup_lng }}">
                  </div>
                  <div class="col-lg-4">
                    <div id="pickup-map"></div>
                    <div id="pickup-infowindow-content">
                      <img src="" width="16" height="16" id="pickup-place-icon" />
                      <span id="pickup-place-name" class="title"></span><br />
                      <span id="pickup-place-address"></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <input type="hidden" name="step" value="2">
            <button type="button" class="btn btn-outline-warning"
              onclick="$('#pills-info-tab').tab('show');">Back</button>
            <button type="submit" class="btn btn-warning">Save & Continue</button>
          </form>
        </div>

        <!-- Step 3 -->
        <div class="tab-pane fade {% if step == 3 %}show active{% endif %}" id="pills-delivery" role="tabpanel"
          aria-labelledby="pills-delivery-tab">
          <h1>Delivery</h1>

          <form method="POST" enctype="multipart/form-data">
            <b class="text-secondary">Delivery Information</b><br />
            <div class="card bg-white mt-2 mb-5">
              <div class="card-body">

                <div class="row">
                  <div class="col-lg-8">
                    {% csrf_token %}
                    {% bootstrap_form step3_form exclude='delivery_lat, delivery_lng' %}
                    <input hidden id="delivery_lat" name="delivery_lat" value="{{ job.delivery_lat }}" />
                    <input hidden id="delivery_lng" name="delivery_lng" value="{{ job.delivery_lng }}">
                  </div>
                  <div class="col-lg-4">
                    <div id="delivery-map"></div>
                    <div id="delivery-infowindow-content">
                      <img src="" width="16" height="16" id="delivery-place-icon" />
                      <span id="delivery-place-name" class="title"></span><br />
                      <span id="delivery-place-address"></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <input type="hidden" name="step" value="3">
            <button type="button" class="btn btn-outline-warning"
              onclick="$('#pills-info-tab').tab('show');">Back</button>
            <button type="submit" class="btn btn-warning">Save & Continue</button>
          </form>
        </div>

        <!-- Step 4 -->
        <div class="tab-pane fade {% if step == 4 %}show active{% endif %}" id="pills-payment" role="tabpanel"
          aria-labelledby="pills-payment-tab">
          <h1>Payment</h1>

          <form method="POST">
            <b class="text-secondary">Payment Method</b>
            <div class="card bg-white mt-2 mb-5">
              <div class="card-body">
                {% csrf_token %}
                <div class="form-group">
                  <label>Your Credit/Debit Card</label>
                  <input class="form-control" value="**** **** **** {{ request.user.customer.stripe_card_last4 }}"
                    disabled>
                </div>
                <div class="form-group">
                  <label>Price</label>
                  <input class="form-control" value="${{ job.price }}" disabled>
                </div>
              </div>
            </div>
            <input type="hidden" name="step" value="4">
            <button type="button" class="btn btn-outline-warning"
              onclick="$('#pills-delivery-tab').tab('show');">Back</button>
            <button type="submit" class="btn btn-warning">Create Job</button>
          </form>
        </div>
      </div>

    </div>
  </div>
</div>

<script>
  var pickupLat = parseFloat('{{ job.pickup_lat }}');
  var pickupLng = parseFloat('{{ job.pickup_lng }}');

  var deliveryLat = parseFloat('{{ job.delivery_lat }}');
  var deliveryLng = parseFloat('{{ job.delivery_lng }}');

  function initMapByType(type, initLat, initLng) {
    const map = new google.maps.Map(document.getElementById(type + "-map"), {
      center: { lat: initLat || -33.8688, lng: initLng || 151.2195 },
      zoom: 13,
    });

    if (initLat && initLng) {
      new google.maps.Marker({
        position: new google.maps.LatLng(initLat, initLng),
        map: map,
      })
    }

    const input = document.getElementById("id_" + type + "_address");
    const autocomplete = new google.maps.places.Autocomplete(input);
    // Bind the map's bounds (viewport) property to the autocomplete object,
    // so that the autocomplete requests use the current map bounds for the
    // bounds option in the request.
    autocomplete.bindTo("bounds", map);
    // Set the data fields to return when the user selects a place.
    autocomplete.setFields(["address_components", "geometry", "icon", "name"]);
    const infowindow = new google.maps.InfoWindow();
    const infowindowContent = document.getElementById(type + "-infowindow-content");
    infowindow.setContent(infowindowContent);
    const marker = new google.maps.Marker({
      map,
      anchorPoint: new google.maps.Point(0, -29),
    });
    autocomplete.addListener("place_changed", () => {
      infowindow.close();
      marker.setVisible(false);
      const place = autocomplete.getPlace();

      if (!place.geometry) {
        // User entered the name of a Place that was not suggested and
        // pressed the Enter key, or the Place Details request failed.
        window.alert("No details available for input: '" + place.name + "'");
        return;
      }

      // If the place has a geometry, then present it on a map.
      if (place.geometry.viewport) {
        map.fitBounds(place.geometry.viewport);
      } else {
        map.setCenter(place.geometry.location);
        map.setZoom(17); // Why 17? Because it looks good.
      }
      marker.setPosition(place.geometry.location);
      marker.setVisible(true);
      let address = "";

      if (place.address_components) {
        address = [
          (place.address_components[0] &&
            place.address_components[0].short_name) ||
          "",
          (place.address_components[1] &&
            place.address_components[1].short_name) ||
          "",
          (place.address_components[2] &&
            place.address_components[2].short_name) ||
          "",
        ].join(" ");
      }
      infowindowContent.children[type + "-place-icon"].src = place.icon;
      infowindowContent.children[type + "-place-name"].textContent = place.name;
      infowindowContent.children[type + "-place-address"].textContent = address;
      infowindow.open(map, marker);

      $("#" + type + "_lat").val(place.geometry.location.lat());
      $("#" + type + "_lng").val(place.geometry.location.lng());
    });
  }

  function initMap() {
    initMapByType("pickup", pickupLat, pickupLng);
    initMapByType("delivery", deliveryLat, deliveryLng);
  }
</script>

{% endblock %}

fastparcel/fastparcel/core/templates/customer/jobs.html
{% extends 'customer/base.html' %}

{% block main %}

{% url 'customer:current_jobs' as current_jobs_url %}
{% url 'customer:archived_jobs' as archived_jobs_url %}

<!-- TABS -->
<ul class="nav nav-pills nav-fill">
  <li class="nav-item">
    <a class="nav-link {% if request.path == current_jobs_url %}active{% endif %}"
      href="{% url 'customer:current_jobs' %}">Current Job</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if request.path == archived_jobs_url %}active{% endif %}"
      href="{% url 'customer:archived_jobs' %}">Archived Jobs</a>
  </li>
</ul>

<!-- LIST OF JOBS -->
<div class="list-group mt-3">
  {% if jobs %}

  {% for job in jobs %}
  <a href="{% url 'customer:job' job.id %}" class="list-group-item list-group-item-action">
    <div class="media">
      <img src="{{ job.photo.url }}" class="rounded-lg mr-3" width="100" height="100">
      <div class="media-body">
        <div class="row">

          <div class="col-lg-9">
            <h5 class="mb-1">{{ job.name }}</h5>
            <p>{{ job.description }}</p>

            <div class="d-flex mb-4">
              <i class="fas fa-map-marker-alt"></i>
              <div class="ml-2">
                <b>{{ job.pickup_name }}</b><br />
                <small>{{ job.pickup_address }}</small>
              </div>
            </div>
            <div class="d-flex">
              <i class="fas fa-flag-checkered"></i>
              <div class="ml-2">
                <b>{{ job.delivery_name }}</b><br />
                <small>{{ job.delivery_address }}</small>
              </div>
            </div>
          </div>

          <div class="col-lg-3 text-right d-flex flex-column justify-content-between">
            <div><span class="badge badge-warning mb-2">{{ job.get_status_display }}</span></div>
            <h2 class="mb-1">${{ job.price }}</h2>
          </div>

        </div>
      </div>
    </div>
  </a>

  {% endfor %}

  {% else %}
  <div class="card">
    <div class="card-body text-center">
      Nothing to show here yet.
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}